feat(RAN-45): Реализовать PoC классификацию на основе BERT
RepoAnalyzer/issue-classifier pull request #2
Opened 2023-03-12 15:36 UTC by DeadlySquad13

Closes issue [RAN-45]

# Summary
Позаимствовал большую часть кода от индусов. Естественно, не обошлось без ошибок и легаси, поэтому буду рад советам по исправлению / улучшению.

В задаче https://repo-analyzer.atlassian.net/browse/RAN-49 перейду от notebook'а к полноценному модулю.

[RAN-45]: https://repo-analyzer.atlassian.net/browse/RAN-45

2023-03-12 15:54 UTC, DeadlySquad13 commented
Увидеть результаты выполнения ячеек в notebook можно, нажав на просмотр файла:
![image](https://user-images.githubusercontent.com/46250621/224556313-7b860ba7-9e11-496f-878b-2dc871f6a165.png)

Код ревьювить можно через синхронизированный файл bert.ju.py.

---
Для более удобного ревью есть расширение https://github.com/marketplace/review-notebook-app/plan/MDIyOk1hcmtldHBsYWNlTGlzdGluZ1BsYW4yMDIz#pricing-and-setup
Но оно не добавляется на аккаунт организации, пишет, что "какая-то проблема с аккаунтом, решим в течение 48 часов". Однако интуиция мне подсказывает, что в бесплатным организациям, как и многие другие вещи в GitHub, это расширение не получится добавить бесплатно.

2023-03-13 15:32 UTC, Nbslab commented on src/issue_classifier/bert.ju.py
> +    random_state=42,
random_seed тоже вынести бы в отдельную ячейку к другим сидам (181-185 строка у тебя), это тоже важная константа, отвечающая за воспроизоводимость. Также хорошей практикой у нас на курсах считалось вынести все сиды, которые мы фиксируем в ноутбуке в самое его начало, следом за ячейкой с импортом либ. Я понимаю, что ты уйдешь от ноутбука в будущем, но random_seed train_test_split-a точно важная константа, которую надо не потерять и в модулях

2023-03-13 15:50 UTC, Nbslab commented on src/issue_classifier/bert.ju.py
> +df["label"] = df.Conference.replace(label_dict)
Красиво сделал, но чтобы не пере изобретать велосипед эту же операцию сделать можно используя fit_transform() LabelEncoder-ом из sklearn

https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelEncoder.html

2023-03-13 15:54 UTC, Nbslab commented on src/issue_classifier/bert.ju.py
> +df.Conference.value_counts()
Дисбаланс однозначно есть, но не сказал бы, что он значительный(99% к 1% например). Если ты в будущем планировал от этого вывода двигаться в своих исследованиях в какую-либо сторону, то я бы попробовал сначала проигнорировать данную особенность распределения и поэкспериментировать с тем, что есть

2023-03-13 16:05 UTC, DeadlySquad13 commented on src/issue_classifier/bert.ju.py
> +    random_state=42,
Я планировал константы оставлять там, где они используются. Условно, если делить по заголовкам, сформированным у меня в notebook'е:
```
issue_classifier/
|
|--common/
|   |--common.constants
|   |--common.utils
|
|-- validation_split/
|   |-- validation_split.py
|   |-- validation_split.constants.py
|   |-- validation_split.utils.py
|
|-- training_loop/
    |-- training_loop.py
    |-- training_loop.constants.py

...
```
То, например, есть какие-то переменные, относящиеся только к validation & split были бы в модуле validation_split, в файле validation-split.constants.py.

Думаешь, есть смысл все сиды в common вынести?

---
(структуру конечно нужно бы у кого-нибудь спереть, насколько я помню в ds & ml есть устоявшиеся названия)

2023-03-13 16:07 UTC, DeadlySquad13 commented on src/issue_classifier/bert.ju.py
> +df["label"] = df.Conference.replace(label_dict)
Мудрость индусов. Меня еще больше смутило, что лейблы получаются несбалансированными:
```py
{'VLDB': 0, 'ISCAS': 1, 'SIGGRAPH': 2, 'INFOCOM': 3, 'WWW': 4}
```
Не знаю, может в этом алгоритме это не роляет...

2023-03-13 16:15 UTC, DeadlySquad13 commented on src/issue_classifier/bert.ju.py
> +df.Conference.value_counts()
Спасибо.  В tag'ах issue github приблизительно такой же баланс, как и в этом датасете, поэтому, думаю есть смысл добавить это в исследование. В таком случае сплитить по всему набору данных, а не по классам?

2023-03-13 17:16 UTC, Nbslab requested changes
# Ревью торч кода
У меня не очень много опыта написания своего кода на торче, и файн-тюнинг я тоже себе не писал, поэтому я хоть и постарался отметить какие то моменты, но много вещей, которые можно улучшить, я наверняка упустил, бест практис еще сам не весь знаю 😢 . Если для нас норм подход с многократным возвращением, то я поищу что нибудь по этой теме и мб в будущих ревью дам какие то правки к этому коду. Ну и проблема с тем, что я не в курсе, какой код потом пойдет дальше в модули и как(описал ниже) тоже усложняет процесс ревью. 

# Общие мысли по структуре
Я тут больше напишу про сложности с ревью именно юпитер ноутбука. 

Здорово, что ты организовал возможность через ju.py формат делать ревью, но когда ты говоришь, что от ноутбука уйдешь в следующей итерации, то встает вопрос, какой код ты собственно оставишь в модулях, а какой написан только для ноутбука. Я пока вижу несколько вариантов: 

- 1 модуль = 1 ноутбук, и убрать тот код, что не пойдет в финальные .py модули, если это не EDA. Данные и модельки можно между ними переносить выгружая и сохраняя их, так будет чище и проще каждый отдельный этап смотреть и фиксить, если надо
- 1 ноутбук = все модули, опять же без лишнего кода, т.е. прям из ячеек с кодом делаешь кцкв и готово. Так весь эксперимент будет виден разом, что тоже имеет свои плюсы погружения в контекст, но модули нужно будет по блокам побить, например заголовками
- 1 модуль - 0 ноутбуков. Ну тут я собственно к тому, что ноутбук тяжко проверять и можно к нему даже не приходить, а все же сразу писать по модулям
- Понимая иногда необходимость поглиномесить в ноутбуке, есть еще вариант код, который будет использоваться как модули сразу писать в модули и импортить в ноутбук. Тогда у тебя в ноутбук сохранит свою функцию исследований и погружения в единый контекст, но код будет сразу структурирован и его будет проще версионировать и ревьюить. Что то такое делают в [VK](https://habr.com/ru/company/vk/blog/662734/)

2023-03-13 17:16 UTC, Nbslab commented on src/issue_classifier/bert.ju.py
> +torch.cuda.manual_seed_all(seed_val)
У торча есть еще один параметр воспроизводимости, который я в своих экспериментах фиксирую `torch.use_deterministic_algorithms()`

https://pytorch.org/docs/stable/notes/randomness.html
https://pytorch.org/docs/stable/generated/torch.use_deterministic_algorithms.html#torch.use_deterministic_algorithms


И еще немного полезной инфы
Не уверен, что ты столкнулся или столкнешься с этим(если она тебе будет нужна как сервис, то что то пот типу такой обертки тебе мб придется писать на торче https://www.youtube.com/watch?v=K4rRyAIn0R0), но на всякий я расскажу случай: особенность работы PyTorch с сидами в ноутбуке:

Я выше писал, что сиды бы вынести вверх, но это не касается торча в юпитере. Ему нужна фиксация сидов сразу перед запуском самописного класса модели, по хорошему прям в ту же ячейку это впихнуть, иначе воспроизводимости не достигнуть. 

Также если в ноутбуке будешь тестить модельку торча и играться с ее параметрами например, то надо перезапускать заново все ячейки, инициализирующие класс модели и объект оптимизатора, чтобы моделька полностью была новая, а не хранила градиенты и веса с прошлого запуска, что скажется на метриках

2023-03-13 17:16 UTC, Nbslab commented on src/issue_classifier/bert.ju.py
> +    num_labels=len(label_dict),
Ну тут соответственно, если вынесешь в LabelEncoder, то можно будет сделать `len(LabelEncoder().classes_)`, в примерах в доке это есть

2023-03-13 17:16 UTC, Nbslab commented on src/issue_classifier/bert.ju.py
> +    tqdm.write(f"F1 Score (weighted): {val_f1}")
Не смог вычленить в ноутбуке, какой лосс ты используешь в обучении, тыкни мне, пожалуйста, в строку, у меня может глаза замылились и я не замечаю, но по аутпутам в ноутбуке лосс на трейне падает, а на валидации растет, что сигнализирует об оверфите, иногда это полезно, но только пока улучшается интересующая нас метрика(F1 в твоем случае), видел ниже, что ты берешь именно модельку с первой эпохи, но поэкспериментировать точно можно еще с 2 и 3-ей эпохой, 4 и 5 точно не вариант, там целевую метрику штормит уже

2023-03-13 17:16 UTC, Nbslab commented on src/issue_classifier/bert.ju.py
> +        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
nn модуль, как один из основных торчевых модулей можно импортнуть заранее, чтобы такую сосиску ссылок не писать

2023-03-13 17:16 UTC, Nbslab commented on src/issue_classifier/bert.ju.py
> +We will use f1 and accuracy per class.
Советую в твоем случае попробовать метрики, направленные как раз на многоклассовую классификацию, нет гарантий, что они будут работать в нашей бизнес-задаче лучше, но вероятность этого присутствует, по крайней мере на это указывает их теоретическая предрасположенность к решаемой тобой задаче

- sklearn: 
https://scikit-learn.org/stable/modules/model_evaluation.html#multilabel-ranking-metrics
- catboost:  
https://catboost.ai/en/docs/concepts/loss-functions-multiclassification https://catboost.ai/en/docs/concepts/loss-functions-multilabel-classification

2023-03-13 17:16 UTC, Nbslab commented on src/issue_classifier/bert.ju.py
> +    random_state=42,
Твоя структура имеет право на существование, но тогда надо дописывать отдельный гайд к ноутбуку, как добиться воспроизводимости: некоторые ячейки с нуля например можно не выполнять, если ты уже имеешь какой то выполненный результат и хочешь продолжить эксперимент в ноутбуке, или какой то препроцессинг выполняется долго и ты выполнил его лишь раз и сохранил результат в отдельный csv, и больше в этот блок не заходишь. В таком случае можно пропустить фикс этих сидов и результат эксперимента будет другой. Поэтому в ноутбуке все же я стараюсь вынести все сиды чуть ли не в ячейку с импортами, чтобы они точно были фиксированы

Насчет структуры я поищу, где то я видел шаблончики

2023-03-13 17:16 UTC, Nbslab commented on src/issue_classifier/bert.ju.py
> +df.Conference.value_counts()
Это сложный вопрос, я пока еще сам не обладаю достаточной компетенцией, чтобы решать, как в такой ситуации лучше сделать, поэтому я обычно пробую сплитить и по всему набору и по классам и смотрю на результат.

Вообще работа с дисбалансом это сложная тема, особенно если это влияет на метрику. Ты пока действуешь довольно осторожно, не смещая исходное распределение, но если придется, то вот пример того, что надо быть осторожнее с метриками и балансированием, когда целевая метрика – например с [микро-усреднением](https://androidkt.com/micro-macro-averages-for-imbalance-multiclass-classification/), т.е. когда важность каждого класса при подсчете метрики пропорциональна размеру этого класса в выборке. За счет балансирования выборки можно выиграть в качестве на менее представленных классах, но качество на классах, в которых примеров больше всего, упадет, что в сумме негативно скажется на целевой метрике.

2023-03-13 23:16 UTC, DeadlySquad13 commented
> # Ревью торч кода
> У меня не очень много опыта написания своего кода на торче, и файн-тюнинг я тоже себе не писал, поэтому я хоть и постарался отметить какие то моменты, но много вещей, которые можно улучшить, я наверняка упустил, бест практис еще сам не весь знаю 😢 . Если для нас норм подход с многократным возвращением, то я поищу что нибудь по этой теме и мб в будущих ревью дам какие то правки к этому коду. Ну и проблема с тем, что я не в курсе, какой код потом пойдет дальше в модули и как(описал ниже) тоже усложняет процесс ревью.
> 
> # Общие мысли по структуре
> Я тут больше напишу про сложности с ревью именно юпитер ноутбука.
> 
> Здорово, что ты организовал возможность через ju.py формат делать ревью, но когда ты говоришь, что от ноутбука уйдешь в следующей итерации, то встает вопрос, какой код ты собственно оставишь в модулях, а какой написан только для ноутбука. Я пока вижу несколько вариантов:
> 
> * 1 модуль = 1 ноутбук, и убрать тот код, что не пойдет в финальные .py модули, если это не EDA. Данные и модельки можно между ними переносить выгружая и сохраняя их, так будет чище и проще каждый отдельный этап смотреть и фиксить, если надо
> * 1 ноутбук = все модули, опять же без лишнего кода, т.е. прям из ячеек с кодом делаешь кцкв и готово. Так весь эксперимент будет виден разом, что тоже имеет свои плюсы погружения в контекст, но модули нужно будет по блокам побить, например заголовками
> * 1 модуль - 0 ноутбуков. Ну тут я собственно к тому, что ноутбук тяжко проверять и можно к нему даже не приходить, а все же сразу писать по модулям
> * Понимая иногда необходимость поглиномесить в ноутбуке, есть еще вариант код, который будет использоваться как модули сразу писать в модули и импортить в ноутбук. Тогда у тебя в ноутбук сохранит свою функцию исследований и погружения в единый контекст, но код будет сразу структурирован и его будет проще версионировать и ревьюить. Что то такое делают в [VK](https://habr.com/ru/company/vk/blog/662734/)

Я к варианту с 0 ноутбуков планировал перейти. Как ты и говорил, можно использовать ноутбук просто для прощупывания почвы, и оставлять его просто как артефакт исследования для потомков. В данном случае этот артефакт в особенности для нас важен, так как его большая часть пойдет в диплом. В моем случае, я, например, если время позволит, хотел туда всунуть какое-нибудь сравнение других методов классификации, чтобы работа была содержательнее.

2023-03-13 23:57 UTC, DeadlySquad13 commented
> # Ревью торч кода
> У меня не очень много опыта написания своего кода на торче, и файн-тюнинг я тоже себе не писал, поэтому я хоть и постарался отметить какие то моменты, но много вещей, которые можно улучшить, я наверняка упустил, бест практис еще сам не весь знаю 😢 . Если для нас норм подход с многократным возвращением, то я поищу что нибудь по этой теме и мб в будущих ревью дам какие то правки к этому коду. Ну и проблема с тем, что я не в курсе, какой код потом пойдет дальше в модули и как(описал ниже) тоже усложняет процесс ревью.

Да, многократно возвращаться - это хорошая практика. В сложных вещах по типу исследований без нее вообще никак. Главное сильно не досаждать и не затягивать, чтобы мр не зависал надолго и человек не перегорал от него (то есть 2 дня максимум на ревью). В данном случае это не сильно критично, так как я только в следующее воскресенье присяду вновь.

2023-03-26 11:11 UTC, DeadlySquad13 commented on src/issue_classifier/bert.ju.py
> +    random_state=42,
Спасибо! Будет выполнено в [RAN-49](https://repo-analyzer.atlassian.net/browse/RAN-49).

2023-03-26 11:18 UTC, DeadlySquad13 commented on src/issue_classifier/bert.ju.py
> +We will use f1 and accuracy per class.
Спасибо! Будет выполнено в [RAN-51](https://repo-analyzer.atlassian.net/browse/RAN-51).

2023-03-26 14:49 UTC, DeadlySquad13 commented on src/issue_classifier/bert.ju.py
> +df["label"] = df.Conference.replace(label_dict)
Сделал

2023-03-26 14:49 UTC, DeadlySquad13 commented on src/issue_classifier/bert.ju.py
> +    num_labels=len(label_dict),
Поменял.

2023-03-26 14:51 UTC, DeadlySquad13 commented on src/issue_classifier/bert.ju.py
> +        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
Импортнул torch чуть повыше.

2023-03-26 15:00 UTC, DeadlySquad13 commented on src/issue_classifier/bert.ju.py
> +    tqdm.write(f"F1 Score (weighted): {val_f1}")
Лосс встроен в модельку ([BertForSequenceClassification](https://huggingface.co/docs/transformers/model_doc/bert#transformers.BertForSequenceClassification)). Видно, как достаем на 219-221 строках: мы инпуты подаем в модель, она нам возвращает loss и logits. В доке не вижу, как именно он расчитывается, ответить сам тоже не могу.

Автор статьи, на которую я ориентировался, написал, что с этим датасетом дальше 5 эпохи нетсмысла крутить, и самой хорошей получилась 1-ая. Я думаю, на данный момент доверюсь ему, а когда начну работать с полным датасетом (https://repo-analyzer.atlassian.net/browse/RAN-50), посмотрим этот момент поподробнее.

2023-03-26 15:34 UTC, DeadlySquad13 commented on src/issue_classifier/bert.ju.py
> +torch.cuda.manual_seed_all(seed_val)
Благодарю.

Моделька не так долго строится, поэтому поставил настройку с детерменированными алгоритмами.

2023-03-26 15:53 UTC, DeadlySquad13 commented on src/issue_classifier/bert.ju.py
> +torch.cuda.manual_seed_all(seed_val)
А не, отмена, BERT не может с этой настройкой работать на моей версии cuda.

2023-03-29 20:06 UTC, Nbslab approved these changes

2023-03-29 20:07 UTC, Nbslab commented
Все гуд, сегодня итак это обсуждали заодно ирл

2023-03-30 10:22 UTC, Nbslab commented on src/issue_classifier/bert.ju.py
> +    tqdm.write(f"F1 Score (weighted): {val_f1}")
Поясню, зачем я начал поднимать тему лосса. Я там описывал признаки оверфита, но по-хорошему это так работает когда ты знаешь, как должен вести себя твой лосс. Для этого надо собственно знать, что за лосс функцию ты используешь, иначе сложно понять, как интерпретировать получаемое число.

Как я уже писал, в общем случае ты поступаешь верно, берешь оптимальную модель, просто для полноты картины понимать бы какая лосс функция используется и как она должна себя вести. Можно ведь лоссом по большому счету любую функцию выбрать, и уменьшение ее значения не будет означать улучшение качества

2023-03-30 11:08 UTC, DeadlySquad13 commented on src/issue_classifier/bert.ju.py
> +    tqdm.write(f"F1 Score (weighted): {val_f1}")
Хорошо, я постараюсь эту инфу поискать в статейках. Пока что вмержу мр, так как по логике не сильно мешает.

2023-03-30 11:09 UTC, merged